{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vestige.fullname" . }}-auth
  labels:
    {{- include "vestige.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | b64enc | quote }}
{{- end }}
